services:
  - type: web
    name: cosmic-watch-api
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NASA_API_KEY
        sync: false
      - key: NASA_API_BASE_URL
        value: https://api.nasa.gov/neo/rest/v1
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_URL
        sync: false
